import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./styles/globals.css";

const NotoSansThai = Noto_Sans_Thai({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={NotoSansThai.className}>
      <body>{children}</body>
    </html>
  );
}
